apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}  # LoadBalancer service type
  ports:
    - port: {{ .Values.service.port }}             # Service port
      targetPort: {{ .Values.service.port }}       # Target port
  selector:
    app: {{ .Release.Name }}

