apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web-server
  name: developer-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

